### ISSUE TITLE
[Bug]: "No changes to commit", "Pull failed fatal: could not read Username for github.com"

### ISSUE THREAD

**Issue by ReaderGuy42** [Vinzent03/obsidian-git#125]
### Describe the bug

I'm new and trying to commit something to my private repo. However I get above error message. I'm not sure where I'm supposed to input my username etc.?

I have Github Desktop set up and I can then manually push commits that I tried committing in Obsidian, but shouldn't there be a way to commit directly from Obsidian without having to do this through Github Desktop?

Thanks (I'm on Linux, and I can't find any tutorials that work for me)

### Steps to reproduce

"Create Backup" -> "No changes to commit", cannot read username.

### Operating system

Linux

**Comment by Vinzent03** [comment]
@ReaderGuy42 You have to either cache the credentials over http in git or use [ssh](https://github.com/denolehov/obsidian-git/wiki#ssh-authentication). Authentication is the biggest problem and I'm unsure how to properly solve it.

@NifleySnifley It's strange that it call the github cli. I don't think it includes a git implementation. (I assume you didn't change the git binary path in the settings). Password authentication is deprecated, but instead you have to enter a personal token, which you can generate on GitHub.

**Comment by aoot** [comment]
@ReaderGuy42 You want to make sure that 1) [Git](https://git-scm.com/downloads) is installed and 2) Install either Git CLI or GCM Core to cache your credentials.

I personally resolved mine (POP OS) using Git CLI and it works like a charm!
