### ISSUE TITLE
[Bug]: Error: Src refspec main does not match any error:failed to push some refs

### ISSUE THREAD

**Issue by callumgourlay** [Vinzent03/obsidian-git#126]
### Describe the bug

When trying to create backup i recieve this error
![Screenshot 2021-10-20 171855](https://user-images.githubusercontent.com/65352339/138132014-e6c2d765-d39e-41ce-8f95-4de81f9034b7.png)
 

### Steps to reproduce

Attempt to push backup

### Operating system

Windows

**Comment by saswatm78** [comment]
@callumgourlay I am having the same issue, have been having it around the same Oct timeframe but was not very proficient with Git so thought maybe I was doing something wrong. I am able to manually push the files using suggestion that @denolehov  provided above but the plugin continues to throw the same error.
<img width="217" alt="Obsidian Git Plugin error" src="https://user-images.githubusercontent.com/66322427/148671786-cbee7936-922e-47ec-ba97-3a91e27fed2f.png">

Can you explain what you meant by copying all the git folders, are you copy all the contents of the .git folder into each and every nested folder in your vault? appreciate  your help.

@denolehov Thank you for the plugin it used to work like a charm for me until this happened.

**Comment by callumgourlay** [comment]
I managed to sort it by creating a new repository and copying the .git folder from one to another. Other than that I don’t remember much of it as it was a while ago now

The information transmitted, including attachments, is intended only for the person(s) or entity to which it is addressed and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited.  If you received this in error, please contact the sender and destroy any copies of this information.
________________________________
