### ISSUE TITLE
Large File Storage

### ISSUE THREAD

**Issue by zharinov** [Vinzent03/obsidian-git#14]
@denolehov, thank you for this plugin!

I tried to use `git-lfs` feature for my images sub-folder and here is error in my console:
```
This repository is configured for Git LFS but 'git-lfs' was not found on your path.
If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
```

Basically, hook content looks like this:
```
#!/bin/sh
command -v git-lfs && git lfs pre-push "$@"
```

I wonder if this can be fixed just by passing parent `PATH` via [this option](https://github.com/steveukx/git-js#environment-variables).

More context:
Obsidian: `0.9.14`
OS: macOS Big Sur

To reproduce, I guess it would be enough to follow [this setup](https://git-lfs.github.com/).
Also, maybe I'll be able to figure out obsidian plugin development setup and debug it on my own.

UPD. As I can see, `obsidian` process doesn't contain `/usr/local/bin` directory in its `PATH`, i.e. it uses system-wide `git` command instead of homebrew-installed one.

**Comment by denolehov** [comment]
Hey, I will look into this closer to next weekend. Sorry for the late reply.

**Comment by danmichaelo** [comment]
Similar issue to #21, but in the case of git-lfs, I [don't think](https://github.com/git-lfs/git-lfs/issues/2895) there is a git-config option to set the path to git-lfs. So perhaps the best would be to introduce two new plugin options: "Path to git" and "Path to git-lfs"?

**Comment by Larandar** [comment]
Ok I think I have the same problem with `gpg`, which the plugin could not find in the path. It might be a problem from simple-git?

**Comment by sascha-wolf** [comment]
I've encountered the same issue.

My solution was to manually update the installed `.git/hooks` and add the following line at the top of each one:

```bash
PATH="$PATH:/usr/local/bin"
```
(*This assumes that the `git-lfs` binary resides in `/usr/local/bin`, which is the case if you installed it through `brew` by example.*)

This will update the `PATH` variable for the scope of the script and not impact your "usual" `PATH`, and as such can be considered safe.

**Comment by frankreporting** [comment]
Tried the above recommendation but still got errors. 

```Cannot add files: git-lfs
filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly```

I checked git-lfs location with `which` and it was usr/local/bin, added that path line in the top of each hook.. though was I supposed to update them some other way first, or is that what sascha-wolf meant by manually updating? Any other ideas what could be causing it to fail?

**Comment by cor** [comment]
This is still an issue as of 2021-09-01

**Comment by mracette** [comment]
I had the same issue as @frankreporting when I installed `git-lfs` using homebrew (`git-lfs` location was `/opt/homebrew/bin`).

To resolve it, I installed it by downloading the package at https://git-lfs.github.com/ and running install.sh, which installed `git-lfs` `/usr/local/bin` (you may also be able to just move the binary).

After that, I was able to add `PATH=$PATH:/usr/local/bin` to the git hooks and after restarting Obsidian everything worked.

**Comment by sascha-wolf** [comment]
> @sascha-wolf Why should I do that? My git-lfs binary is already in the path.

If it works for you, you don't. It didn't for me, git-lfs wasn't in the `PATH` of the script execution.

**Comment by christyray** [comment]
Like @frankreporting and @mracette, I was having the same issue where it still wasn't working even after I added `PATH="$PATH:/usr/local/bin"` to the top of each git hook. 

I didn't want to download and install `git-lfs` manually since I wanted to maintain the management by Homebrew. I was specifically getting an error message about `filter-process`, and I realized that was part of the filters Git LFS defines in the `.gitconfig`. 

I updated my global `.gitconfig` to refer to `/usr/bin/local/git-lfs` instead of just `git-lfs` on all of the filter lines. That combined with adding `PATH="$PATH:/usr/local/bin"` to the top of each git hook fixed it for me!

That section of my global `.gitconfig` now looks like:

```
[filter "lfs"]
	process = /usr/local/bin/git-lfs filter-process
	required = true
	clean = /usr/local/bin/git-lfs clean -- %f
	smudge = /usr/local/bin/git-lfs smudge -- %f
```

**Comment by finn-matti** [comment]
Thanks @christyray, your tip solved it for me!

You can put that section also inside the `.git/config` file of the Obsidian repo itself, if you don't want to change your global `.gitconfig` file.

**Comment by AlekseiCherkes** [comment]
If you don't want to modify `gitconfig` or git hooks you can create `git.sh` file in the root dir of your vault or anywhere else you want then specify it as a git command in "Obsidian Git" settings.

```
#!/bin/bash

# Implementation of git command with Homebrew binaries added to the PATH.
# Needed to make Obsidian Git plugin work with git-lfs. To use this file specify 
# the global global path to this file in "Custom Git binary path" setting of "Obsidian Git".

export PATH=$PATH:/usr/local/bin
/usr/local/bin/git "$@"
```

Works well for me!

**Comment by dwSun** [comment]
> Like @frankreporting and @mracette, I was having the same issue where it still wasn't working even after I added `PATH="$PATH:/usr/local/bin"` to the top of each git hook.
> 
> I didn't want to download and install `git-lfs` manually since I wanted to maintain the management by Homebrew. I was specifically getting an error message about `filter-process`, and I realized that was part of the filters Git LFS defines in the `.gitconfig`.
> 
> I updated my global `.gitconfig` to refer to `/usr/bin/local/git-lfs` instead of just `git-lfs` on all of the filter lines. That combined with adding `PATH="$PATH:/usr/local/bin"` to the top of each git hook fixed it for me!
> 
> That section of my global `.gitconfig` now looks like:
> 
> ```
> [filter "lfs"]
> 	process = /usr/local/bin/git-lfs filter-process
> 	required = true
> 	clean = /usr/local/bin/git-lfs clean -- %f
> 	smudge = /usr/local/bin/git-lfs smudge -- %f
> ```

works for me

**Comment by Vinzent03** [comment]
I've added a setting to add paths to the PATH env var. Can one of you try the new setting?

**Comment by christyray** [comment]
> I've added a setting to add paths to the PATH env var. Can one of you try the new setting?

The new setting doesn't appear to be updating my path, at least based on the output of `process.env.PATH` in the console. But, Obsidian now (and possibly for a while - I haven't checked this recently) seems to be using the PATH variable I have set in `.zshrc`, and that fixed the issues I was having with Git LFS being located.

**Comment by AlekseiCherkes** [comment]
@Vinzent03 Seems to work for me. 
Little notch: the path should be specified with the trailing `/`. Obsidian Git treats it as a path to file (not directory) otherwise.

**Comment by Vinzent03** [comment]
@AlekseiCherkes You mean the settings description should be improved?

**Comment by AlekseiCherkes** [comment]
> @AlekseiCherkes You mean the settings description should be improved?

@Vinzent03 I don't know what's happend exactly, but everything is OK on my side now. I wasn't able to reproduce the issue.

**Comment by fxsalazar** [comment]
> I've added a setting to add paths to the PATH env var. Can one of you try the new setting?

In my case, I had to add `/opt/homebrew/bin/` and it worked.

**Comment by icefed** [comment]
News: 

Add `/opt/homebrew/bin` or your `git-lfs` path in `obsidian-git` setting `Additional PATH environment variable paths` can solve this.

**Comment by frankreporting** [comment]
> > I've added a setting to add paths to the PATH env var. Can one of you try the new setting?
> 
> In my case, I had to add `/opt/homebrew/bin/` and it worked.

This also worked for me. Thank you!

**Comment by JV-conseil** [comment]
Adding 

```shell
/opt/homebrew/bin
```

in 

```shell
Obsidian Git > Advanced > Additional PATH environment variable paths
```

worked for me 👌

![Adding `/opt/homebrew/bin` in Obsidian Git > Advanced > Additional PATH environment variable paths](https://github.com/denolehov/obsidian-git/assets/8126807/ab66fa33-3c82-45ab-a91a-f828a21421db)

Git LFS commit and push now work on Obsidian with `git-lfs` installed with `Homebrew` ✅

**Comment by rlkennedyreid** [comment]
> Adding
> 
> ```shell
> /opt/homebrew/bin
> ```
> 
> in
> 
> ```shell
> Obsidian Git > Advanced > Additional PATH environment variable paths
> ```
> 
> worked for me 👌
> 
> ![Adding /opt/homebrew/bin in Obsidian Git > Advanced > Additional PATH environment variable paths](https://private-user-images.githubusercontent.com/8126807/309779180-ab66fa33-3c82-45ab-a91a-f828a21421db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjcyMDksIm5iZiI6MTcxMTM2NjkwOSwicGF0aCI6Ii84MTI2ODA3LzMwOTc3OTE4MC1hYjY2ZmEzMy0zYzgyLTQ1YWItYTkxYS1mODI4YTIxNDIxZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTE0MTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWM0OGNhNGMxN2U4NDY3NzkwMWJiZjUwYTc0MzA4YjhlYjljMDMwMjQ1ZmY1MmZjNTg5MjllNzZmYzQ0NGNmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gESj8ygYr1xHzCmSwy9eSivYv0vYBpT-SdxrLdvfSDg)
> 
> Git LFS commit and push now work on Obsidian with `git-lfs` installed with `Homebrew` ✅

This also worked for me

**Comment by Vinzent03** [comment]
I've added the needed change to the PATH environment variable to the [docs](https://publish.obsidian.md/git-doc/Integration+with+other+tools#Git+Large+File+Storage). 
Thanks for the many comments on how to fix this.
