### ISSUE TITLE
[Bug]: Fatal : could not read from remote repository.Plese make sure you have the correct access rights

### ISSUE THREAD

**Issue by PreX-AW** [Vinzent03/obsidian-git#447]
### Describe the bug

use command `obsidian git push` or`obsidian git pull` show :

![image](https://user-images.githubusercontent.com/96912272/221373352-713734ac-f6a3-4fb4-afb1-331f7134f078.png)

### Steps to reproduce

I clone a repo to my machine( ubuntu 22.04). Everything  about git is OK on terminal ,when i use obsidian to push or pull repo ,something gonna wrong!  

and I try the commands 
```
$ flatpak update md.obsidian.Obsidian
$ flatpak override --reset md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```
but it do not work,and i also try 
```
ssh-add ~/.ssh/id_rsa.pub
```
also useless.

All settings are default ,except `commit author`

### Addition context

Buy the way, I used obsidian git on windows ,and it perform perfectly !
Thanks author! 

### Operating system

Linux

### Installation Method

Flatpak

### Plugin version

2.16.0

**Comment by Vinzent03** [comment]
You may try the answers [here](https://superuser.com/questions/1212402/bad-owner-or-permissions-on-ssh-config-file).

**Comment by PreX-AW** [comment]
> 

Thanks you . I read the link that you mentioned  , and  i try the method .
But it still not work for my situation.
i even change the mode `777` to `.ssh` and `.ssh/*`

**Comment by Vinzent03** [comment]
Then you may try a different install method for Obsidian. E.g. AppImage.

**Comment by PreX-AW** [comment]
Thank you for you suggestion😃, I wandered if any precedents fixed this issue before?
I also want to reinstall git on my machine to solve this issue,but I don't know can it work.🤯
Besides,I wanna see "obsidian logo " instead of a "gear"on my desktop, Please forgive me for being a Linux beginner.😭> Then you may try a different install method for Obsidian. E.g. AppImage.

**Comment by Vinzent03** [comment]
Reinstalling Git won't change anything, as it's an issue with Obsidian not being able to read your ssh config file. I don't know for sure if you get an icon when using AppImage, but think so.

**Comment by PreX-AW** [comment]
> Reinstalling Git won't change anything, as it's an issue with Obsidian not being able to read your ssh config file. I don't know for sure if you get an icon when using AppImage, but think so.

OK , I will try ApppImage later.
Thank you for your suggestion .

**Comment by elvisisvan** [comment]
how do you even able to clone your private repo in the first place?
