### ISSUE TITLE
fatal: could not read Username for 'https://github.com': Device not configured

### ISSUE THREAD

**Issue by AesmaTheFool** [Vinzent03/obsidian-git#461]
Hey There. I've just started using Obsidian Git, after getting everything set up using this [tutorial](https://www.youtube.com/watch?v=XR7PYaMVDw0), I've run into a persistent issue where, every time I backup, I get this error message:

<img width="312" alt="Screen Shot 2023-03-12 at 5 16 03 PM" src="https://user-images.githubusercontent.com/127699550/224583209-0bcffe50-6585-4547-88ad-d20452c2823a.png">

Despite this error message, I am still able to back up with no issues. Downloading the file from the github page doesn't show result in any discrepancies. According to some online solutions, I've tried to fix this error message by changing the URL in the git config file with SSH, but then I end up with this: 

<img width="314" alt="Screen Shot 2023-03-12 at 5 22 31 PM" src="https://user-images.githubusercontent.com/127699550/224583403-f98b0459-23ea-4e61-b044-62265ae2eefe.png">

At this point I can no longer commit. I've since gone back to HTTPS, and the issue was resolved. I'm now wondering how to get rid of this first error message. 

**Addition context**
I'm unsure if this is a bug or if I'm doing something wrong. I've also attempted to follow [this link](https://github.com/denolehov/obsidian-git/issues/254) to no avail. 

**Operating system**
Mac (Apple M1 Chip)

**Comment by Vinzent03** [comment]
Please try the steps described [here](https://publish.obsidian.md/git-doc/Authentication#HTTPS)

**Comment by AesmaTheFool** [comment]
> Please try the steps described [here](https://publish.obsidian.md/git-doc/Authentication#HTTPS)

Sorry man, that doesn't seem to be working either. In case I'm doing something wrong, here's what I did:

1. Opened up Terminal on Mac
2. Copy/Pasted `git config --global credential.helper osxkeychain` as instructed in the link
3. Pressed Enter to run it
4. Committed and pushed the vault
5. Still getting the same error message
6. Repeated Steps 1-3, then I restarted Obsidian and committed/pushed again
7. Still getting the same error message
8. Did the same thing again, except this time I ran Terminal inside Github Desktop
9. Still getting the same error message

For what it's worth, this issue isn't a deal breaker for me. Further testing revealed that the files committed just fine, they just weren't being pushed so I manually do that.

**Comment by Vinzent03** [comment]
Hmm strange, I don't have a macos device myself, so I can't really test this. Thought that would solve the issue. After setting the credential helper and calling e.g. push. Do you have to enter your credentials when you try to push again?

**Comment by AesmaTheFool** [comment]
I haven't received any options to enter my credentials at any point. I did add my info in the plugin settings, but that doesn't seem to change anything either.

**Comment by GJRobert** [comment]
Could this be helpful?

> Use the SSH git clone url (something like git@github.com:bitrise-io/bitrise.io.git) instead of the HTTPS one (https://github.com/bitrise-io/bitrise.io.git). 
  --- [Fatal: could not read Username for 'https://github.com': Device not configured - Question & Answer / Builds - Bitrise Discussions](https://discuss.bitrise.io/t/fatal-could-not-read-username-for-https-github-com-device-not-configured/816)

**Comment by gchoong** [comment]
For Mac and for that command of 
`$ git config --global credential.helper osxkeychain`
make sure that you are in the cd of your vault.

I was also trying to use ssh but I don't think that is working.

**Comment by davidplans** [comment]
Just to update the thread, after credential.helper command, you can generate a fine-grained personal access token on github and use that as the password, which works fine.

**Comment by arifardia** [comment]
I had the same problem as you, and I solved it with the following command
```$ git config --global credential.helper store```

**Comment by Vinzent03** [comment]
Since osxkeychain seems to work for you all as stated in the [documentation](https://publish.obsidian.md/git-doc/Authentication#macOS) I'm going to close this now.
