### ISSUE TITLE
[Bug]: ssh_askpass error intermittently popping up

### ISSUE THREAD

**Issue by declanoller** [Vinzent03/obsidian-git#498]
### Describe the bug

I had obsidian-git working on this machine flawlessly for a while, but in the recent past (I believe coinciding with github changing their keys), it has started popping up this error when trying to sync:
![obsidian_askpass_ssh](https://user-images.githubusercontent.com/32557146/233257451-fa89f603-78c7-4e5e-984e-698d079dfd7b.png)

```
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

However, git works everywhere else on my machine, and in fact, if I go to my vault directory and manually do `git pull`, `git commit -am "blah blah"`, `git push`, it all works fine.

In fact, I think that it was even sometimes working intermittently despite also saying this error!

I uninstalled and reinstalled obsidian-git, and now it appears to reliably sync, but it still *also* gives the error, which I would like to remove. What can I try?

### Relevant errors (if available)

```shell
Uncaught (in promise) Error: ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (plugin:obsidian-git:26501:25)
    at PluginStore.exec (plugin:obsidian-git:26526:25)
    at eval (plugin:obsidian-git:24031:43)
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (plugin:obsidian-git:24029:16)
    at GitExecutorChain.eval (plugin:obsidian-git:24013:44)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-git:22858:24)
```

### Steps to reproduce

I don't know how to do this without having exactly my setup

### Expected Behavior

It to sync without the `ssh-askpass` error

### Addition context

Obsidian version 1.1.16
Ubuntu 20.04
git version 2.25.1

I have no idea why it's asking for `ssh-askpass`. On my other machine, with the same exact versions as this one, it doesn't have `ssh-askpass` installed either. 

### Operating system

Linux

### Installation Method

AppImage

### Plugin version

2.19.1

**Comment by Vinzent03** [comment]
May you try installing `ssh-askpass`?

**Comment by declanoller** [comment]
> May you try installing `ssh-askpass`?

Hi @Vinzent03 , I did at one point, and I don't think it fixed the issue. But regardless, I don't have `ssh-askpass` installed on my other computer with nearly identical setup (just Ubuntu 22.04 on other vs 20.04 on this machine), and I don't think I should need it.

I think it should be a big clue that obsidian-git *is* currently working in the sense that it's pulling/committing/pushing successfully, but it's *also* trying to do something with `ssh-askpass`.

**Comment by melekabbassi** [comment]
> May you try installing `ssh-askpass`?

After installing `ssh-askpass`, everytime I try to push it asks for the password and then does the job.

Thank you :heart:

**Comment by Vinzent03** [comment]
It probably needed `ssh-askpass`, because the environment variable `SSH_ASKPASS` was set to that file. I'm closing this, because this depends on your ssh setup.
