### ISSUE TITLE
FrontMatter Exception from .ignore   |   Extention Exception from .ignore

### ISSUE THREAD

**Issue by 7Codez** [Vinzent03/obsidian-git#543]
We are adding, for example, the Folder-db.md file to .ignore
It works as an exception to it and does not backup.
But we have a bug and an annoying thing in frontmater constantly changing for each file.

We need and suggest that you add an option within .ignore to exclude frontmater for all files, because we use applications such as data view , folder db and many similar plugins. The problem lies within the files for the frontmater part, changing FrontMatter part for each file constantly.

Second suggestion:
Add extention exceptions inside .ignore
For example, in the types of files we do not want backup. We will mention extention for a file type and it will make an exception for them without backing up.

**Comment by Vinzent03** [comment]
I guess you mean `.gitignore` with `.ignore`? So you want that frontmatter changes don't get committed for selected files? If so, I don't plan to add that because it's hard to maintain and catch all edge cases. As well I think the frontmatter is part of the file and should be committed as well.
