### ISSUE TITLE
[Bug]: Files in submodules cannot be opened on GitHub

### ISSUE THREAD

**Issue by Gewerd-Strauss** [Vinzent03/obsidian-git#592]
### Describe the bug

When you setup a submodule in your vault and put a note into it, executing `Open file on Github` & `Open file history on GitHub` will fail. Instead of parsing the submodule to get the correct address to built on, the file is assumed to be located in the main repo - which is obviously not the case.

### Steps to reproduce

1. setup obsidian git with an existing repo and have a full sync cycle done
2. create a submodule & push it to GH
3. add a note in said submodule and push it to GH
4. open the note in obsidian
5. attempt to execute either `Open file on Github` or `Open file history on GitHub`.
6. Notice that the run URL is pointing at nothing.

### Expected Behavior

The plugin should notice if a note is in a submodule, figure out what repository the file is actually located in, get its base path and then assemble the path up to the file from there. 

### Operating system

Windows

### Installation Method

None

### Plugin version

2.22.0

**Comment by Gewerd-Strauss** [comment]
Unfortunately, I can still reproduce this issue, using version 2.24.3.

Having a submodule `data` at `<root>/assets/data/`, containing `<root>/assets/data/README.md`, and attempting to execute `Open file on Github` will still run the URL `https://github.com/%user-redacted%/%main_repo%/blob/master/assets/data/README.md`, instead of `https://github.com/%user-redacted%/%submodule_repo%/blob/master/README.md`.

**Comment by Vinzent03** [comment]
The fix is not released yet, but will do so soon.
