### ISSUE TITLE
Git querry in Dataview?

### ISSUE THREAD

**Issue by Triquetra** [Vinzent03/obsidian-git#595]
I'd like to create a list of files using modified within a specific date range. Using Dataview faclities directly only shows the most recently modified date, rather than historical data. It would be nice to be able to use git diff or git log or git whatschanged to obtain the list of files created or modified within a specific date ranege. 

My javascript-fu is weak. Does anyone know if git may be queried for this information from within Dataview?

**Comment by Vinzent03** [comment]
There are some methods on `plugin.gitManager` that can be used to query information. So I think my plugin already provides all needed endpoints. But I'm not going to create a guide for dataview.
