### ISSUE TITLE
[Bug]: fail to pull from Github

### ISSUE THREAD

**Issue by DelmarHuang** [Vinzent03/obsidian-git#631]
### Describe the bug

Hi thank you very much for your program! Could you kindly help me? Thank you again!!

This is a bug and I do not know how to fix it. Here is what happened:
1. I created some notes in Obsidian in my MacBook and pushed them to GitHub.
2. Two weeks after, I tried to pull them in my Lenovo ThinkPad but failed (which succeeded all the time before these new notes). The marks in the path also appeared in other notes. And in the screenshots, it is mentioned that only one note cannot be pulled but actually there are also others that are not pulled which I can see in GitHub. So the bug screenshots are as follow:

![image](https://github.com/denolehov/obsidian-git/assets/54244063/60a2e37c-3aa2-4122-b36e-5b1cae47ef61)

![image](https://github.com/denolehov/obsidian-git/assets/54244063/27c48fcd-08e4-4b9c-88ba-2c20f165361c)

### Steps to reproduce

I only created notes.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.22.0

**Comment by leonadler** [comment]
Your file name includes a question mark "What is El Nino and La Nina?.md"  <--

Question marks are special characters on most operating systems, making them part of a filename creates "mild problems" at best.
Consider to use remove the question mark from the file name, and have a top-level heading (`# Text`) which includes the question mark, or any special character you want.
