### ISSUE TITLE
[Bug]: wrong order in git backup

### ISSUE THREAD

**Issue by LFSaw** [Vinzent03/obsidian-git#718]
### Describe the bug

Merge conflicts when doing `Git: Create backup` in a 2 machine scenario

### Steps to reproduce

+ 2 instances of obsidian vault on different machines (A , B), each with the same obsidian-git settings (apart from machine ID)
+ edit the same file on machine A and B
+ `Git: Create backup` on machine A
+ `Git: Create backup` on machine B

results in merge conflict.

### Expected Behavior

no merge conflict.

This could be achieved by a git command sequence within `Git: Create backup`:

1. `git commit`
2. `git pull [--rebase]`
3. `git push`

### Operating system

macOS

### Installation Method

None

### Plugin version

2.24.1

**Comment by Vinzent03** [comment]
I don't think this is an issue with the plugin. You just create a merge conflict, which the plugin can't solve more than git. You can set rebase to be used when pulling in the settings.

**Comment by LFSaw** [comment]
Thanks for taking the time looking into this!

I'd just like to have configuration in which I can save changes from both machines (as in the above scenario) in one action (per machine) without creating a merge conflict. 
I just tried using the "rebase" setting; unfortunately this does not change that I get an error message, however, it seems not to create a merge conflict...

The sequence

1. edit file `example.md` on machine A
1. edit file `example.md` on machine B (different edit)
2. Git: Create backup on machine A
2. git commit on machine B
4. `git pull --rebase` on machine B
5. `git push` on machine B

works for me without a merge conflict and without an error (given that an automatic merge is possible).

**Comment by Vinzent03** [comment]
Please share your error messsage. So you are editing the file in two different places, right?
