### ISSUE TITLE
[Bug]: There is a bug in the ”discard“ feature.

### ISSUE THREAD

**Issue by fantab01** [Vinzent03/obsidian-git#734]
### Describe
When a complex md file uses the discard function, it will show that the file has been changed when switching to reading mode, but when clicking the diff view, it will show that there is no difference.（The gif is recorded in a sandbox environment. The only change to the sandbox environment is to install the git plugin.）

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
SYSTEM INFO:
	Obsidian version: v1.6.3
	Installer version: v1.5.12
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Git v2.24.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Steps to reproduce

[Special notes for reproducing bugs.md](https://github.com/user-attachments/files/15751169/Special.notes.for.reproducing.bugs.md)
![bug](https://github.com/denolehov/obsidian-git/assets/45958766/a3384bb6-2da6-4312-aafd-a38eea6f1eb3)

### Expected Behavior

Switching to reading mode shouldn't change the file, right? I'm curious about the cause of this bug.

### Operating system

Windows

### Installation Method

None

### Plugin version

v2.24.2

**Comment by Vinzent03** [comment]
Please execute the `git diff <path to your file>` command in the terminal to see the actual diff. But I agree that switching to reading more shouldn't change the file itself.

**Comment by fantab01** [comment]
> Please execute the `git diff <path to your file>` command in the terminal to see the actual diff. But I agree that switching to reading more shouldn't change the file itself.

Thank you for your advice, it was very helpful. This is yet another classic line ending issue, and I have resolved it.
![image](https://github.com/denolehov/obsidian-git/assets/45958766/2748b17a-d7c4-464f-a07c-166e276e1997)

**Comment by Vinzent03** [comment]
This plugin doesn't touch your file when switching to reading mode, that has to be Obsidian. I think the plugin is working mostly correctly. The only issue is that the diff view doesn't show that the line endings have changed, but from what I know that's typical for diff views.
