### ISSUE TITLE
[Feature Request] Add support for termux git for Android

### ISSUE THREAD

**Issue by EvilsSouls** [Vinzent03/obsidian-git#752]
As isomorphic-git is very unstable, I suggest there being an option to use termux with git installed, instead of it.

**Comment by noomly** [comment]
There are already a bunch of issues on the subject. As I understood it, there is no way for obsidian-git to get access to Termux. The most promising approach seems to be switching to wasm-git, but there appear to remain a few roadblocks. See this issue https://github.com/Vinzent03/obsidian-git/issues/572. There wasn't much activity on it recently but as I got interested in the issue I'll probably get a shot at it soon

**Comment by EvilsSouls** [comment]
> There are already a bunch of issues on the subject. As I understood it, there is no way for obsidian-git to get access to Termux. The most promising approach seems to be switching to wasm-git, but there appear to remain a few roadblocks. See this issue https://github.com/Vinzent03/obsidian-git/issues/572. There wasn't much activity on it recently but as I got interested in the issue I'll probably get a shot at it soon

I actually researched it a bit and there does seem to be a way for [3rd party apps to interface with Termux](https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent). The only issue I see, is that you'd always have to have a Termux session open, that Obsidian can communicate to. Technically you can fix this by making a daemon that starts on boot (using Termux) which automatically runs the commands it is sent through Obsidian. While these two options would take quite a bit of setting up, I think quite a few users (including me) would rather set it up once and have it function, than keep facing issues with isomorphic-git. Also if this was just an option the users could weigh the pros and cons themselves.

**Comment by Vinzent03** [comment]
This involves sending intents and needs extra permissions in the manifest of Obsidian, which is not possible for a plugin. I'm not aware of a way to access native features on mobile.

**Comment by EvilsSouls** [comment]
> This involves sending intents and needs extra permissions in the manifest of Obsidian, which is not possible for a plugin. I'm not aware of a way to access native features on mobile.

Ah ok. I guess I'll wait for the WASM-git implementation.
