### ISSUE TITLE
Auto backup doesn't stage files? 

### ISSUE THREAD

**Issue by xenide** [Vinzent03/obsidian-git#756]
### Describe the bug

I have auto backup after stopping file edits enabled, and set the vault backup interval to 1 minute. 

But still it doesn't commit and push the changes. Is it because the files are not staged automatically? 

### Steps to reproduce

![Screenshot 2024-07-29 at 11 18 18 PM](https://github.com/user-attachments/assets/ef3d577f-f16d-41ce-b403-ed72a8ea003d)

### Operating system

macOS

### Installation Method

None

### Plugin version

latest

**Comment by steakhutzeee** [comment]
Hi, I'm experiencing the same, but only on Linux. On Windows it works fine. How did you solve it?
