### ISSUE TITLE
Feature: option to disable on mobile

### ISSUE THREAD

**Issue by clehene** [Vinzent03/obsidian-git#759]
It would be useful to have an option to disable the plugin on mobile devices (not just each device which is impractical)

First, using obsidian-git in combination with a file cloud sync (e.g. iCloud) has the potential to corrupt the git repository.
Second, for large repositories it causes Obsidian to sync for a few minutes on every use on a mobile device.

These make the plug-in impractical on mobile devices, so there should at least be an option to disable it across. 
Note there's a flag to have a plugin only work on desktop so, I'm guessing that's accessible to implement the flag.

**Comment by clehene** [comment]
Related issue https://github.com/Vinzent03/obsidian-git/issues/558

**Comment by Vinzent03** [comment]
What about the setting "Disable on this device" at the bottom of the plugin's settings?

**Comment by clehene** [comment]
@Vinzent03 that's the workaround I was saying is impractical. There should be a flag to explicitly enable on mobile devices, instead. I have 4 mobile devices. Moreover Obsidian has a dedicated flag to mark plugins as desktop only. 

The broader problem is that both capabilities and workflows are different on mobile vs desktop. Having a git process churning through a 5GB vault, is not something I want on mobile.

**Comment by Vinzent03** [comment]
On some devices and circumstances, the plugin works on mobile, so I won't mark it as desktop only. As long as you close the history and source control view, the plugin shouldn't scan your whole vault, so you can disable the plugin for that device via the plugins setting.

**Comment by clehene** [comment]
@Vinzent03 I'm not asking to make it desktop only, but to give me an option to make my instance so that I can continue using the git plugin, which currently prevents me from being able to use obsidian on mobile devices. 

I was only referring to the desktop only flag because it was important enough to make it a top level option - and while I understand the use-case to enable it on mobile, there's a good argument to allow disabling it on mobile.

I thought it's a low cost option for a high utility feature that I happen to need, that's it. If that's not the case, please close with won't fix, no problem and thanks for the plugin, I appreciate your work!

**Comment by Vinzent03** [comment]
> As long as you close the history and source control view, the plugin shouldn't scan your whole vault, so you can disable the plugin for that device via the plugins setting.

Have you tried this?

I see no way to offer an option to disable the plugin, without even enabling it. So despite the existing "Disable on this device" setting, I won't provide any other way.
In generally you can always choose a different config directory in the Obsidian settings to not share config at all with desktop.

**Comment by clehene** [comment]
> In generally you can always choose a different config directory in the Obsidian settings to not share config at all with desktop.

Thanks this may be a good strategy to split desktop / mobile config
