### ISSUE TITLE
[Bug]: process.cwd is not a function

### ISSUE THREAD

**Issue by scooper4711** [Vinzent03/obsidian-git#761]
### Describe the bug

I've installed this plugin on MacOS and it's not working. It saying "Git is not ready". Looking in the error logs, I see the following error.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
Uncaught (in promise) TypeError: process.cwd is not a function
    at createInstanceConfig (plugin:obsidian-git:25881:27)
    at gitInstanceFactory (plugin:obsidian-git:29367:18)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29748:18)
```

### Steps to reproduce

running installer 1.6.5 and Obsidian 1.6.7

### Operating system

macOS

### Installation Method

None

### Plugin version

2.25.0

**Comment by Vinzent03** [comment]
That's strange as that's a function provided by Electron, the underlying Software to run Obsidian. Does this happen in the sandbox vault as well with no other plugin installed?

**Comment by scooper4711** [comment]
Very interesting - in an empty vault, it works, and the process object is of class 'process'.
In the vault where it doesn't work, the process object is of class 'Object', and contains only the environment variables...

I'll continue to investigate...

**Comment by scooper4711** [comment]
It appears to be a conflict with the plugin "Sheet plus" - which is an excel spreadsheet plugin. 
https://github.com/ljcoder2015/obsidian-sheet-plus

I'll leave this bug hanging around so that people will know what the solution is if they encounter it, but it's not an issue with your plugin.

**Comment by scooper4711** [comment]
Looks like you are importing process from process, while the other repo is importing process from node:process.

**Comment by cromelex** [comment]
This started happening to me today, is there any tips in finding the cause?
I've tried in a new vault without any other plugins and it worked. So it' probably some other plugin, but I can't seem to find the cause.

Edit: going one by one and I was able to find it. It was obsidian-file-order.
