### ISSUE TITLE
[Feature]: 0-depth history to reduce .git/ size

### ISSUE THREAD

**Issue by doublethefish** [Vinzent03/obsidian-git#763]
There are many benefits to reducing local Vault checkout size. One way, if using git, is being aggressive with `prune` and `--depth`, and only have the last commit sync'd/available.

It would be _very_ nice to have the option to periodically, and optionally, run the equivalent of:
```sh
git fetch --depth 1 --force
git gc --prune=now --aggressive
```

OR it would be nice to be able to periodically run custom git commands. I guess it would be additionally useful to be able to limit these commands specific devices.

## Pros
This can reduce a checkout size of a Vault by hundreds of MB or more, often more than halving the size on disk.

Smaller size-on-disk is useful for:
- working on a storage-limited device (mobile, tablet, raspberry pi, etc.)
- faster distributed sync (for leader-follower architectures with follower-devices that can't use git)
- fast iCloud sync (for iPhone where unsecured http git isn't an option)
- less disk-space usage

## Cons
- no history in Vaults with `--depth 1` option enabled

**Comment by Vinzent03** [comment]
I think that's a highly advanced and uncommon feature. It's already possible to specify the depth on clone, but running this on an existing vault is more uncommon and I think there are better ways than to include that in the plugin. It should be possible to do that in a git hook for example.

**Comment by doublethefish** [comment]
I noticed the mention of a “highly advanced” feature - I'm not sure how that aligns with the expectations for a Git tool. 

For a tangible example, users who rely on iPhones with iCloud may encounter the well-documented file-deletion issue. Without addressing this, these users may face significant challenges using the plugin, especially without a built-in solution. A feature addressing this would be highly valued, particularly until there is support for SSH Git on iPhone (which I believe is currently not supported, correct?).

That being said, the suggestion of using `git-hooks` is interesting. It could serve as a temporary workaround, although it might require ongoing maintenance on each device it was on. It's a good stopgap measure for now.

**Comment by Vinzent03** [comment]
This still is a plugin for a note-taking app and not a full-fledged git client.
I'm unsure if the mobile git library isomorphic-git even supports such reset. Removing most of the history may help with iCloud, but not actually solve sync issues.
I close this issue for now, because I don't plan to implement this feature.
