### ISSUE TITLE
[Bug]: If the git remote address can't established, the plugins can't use and no tips.

### ISSUE THREAD

**Issue by YangAoLib** [Vinzent03/obsidian-git#764]
### Describe the bug

When the git  remote address is not established, the plugin will be unusable with no prompts.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
the console no error info.
```

### Steps to reproduce

1. Remove the `known_host` file from the SSH directory.
2. Open Obsidian.

### Expected Behavior

Display an error message or a pop-up for user confirmation when the URL is not specified.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.23.2

**Comment by Vinzent03** [comment]
I'm unsure what your exact issue is. Can you push or pull? If not please try pulling from the terminal.

**Comment by YangAoLib** [comment]
When I remove the `known_host` file, I can't pull and push in the obsidian.
I can operate in the terminal. 
At first, I didn’t know what caused it until I ran the pull command in the terminal.

So, I think the error tips is necessary.

**Comment by Vinzent03** [comment]
But what exactly happens when you try to pull in Obsidian? Does it just load infinitely? When you pull in the terminal, shouldn't it ask you to re-add the host to the known_host file? So that afterward it works again in Obsidian?

**Comment by YangAoLib** [comment]
Sure, after I pull in the terminal, it can do well.
In Obsidian, nothing transpires. Consequently, we must incorporate prompts within Obsidian to alert users to the presence of an ongoing issue.

**Comment by Vinzent03** [comment]
This should be fixed now in v2.30.0 because the SSH_ASKPASS env variable is set to communicate with Obsidian ui.
