### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Malli88** [Vinzent03/obsidian-git#767]
### Describe the bug

Not able to execute any git command from obsidian-git plugin.
local github connection is working.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
git obsidian error: Cannot run git command
plugin:obsidian-git:30392 Error: spawnSync git ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.setGitInstance (plugin:obsidian-git:29730:14)
    at ObsidianGit.init (plugin:obsidian-git:44090:31)
    at ObsidianGit.isAllInitialized (plugin:obsidian-git:44239:18)
    at ObsidianGit.createBackup (plugin:obsidian-git:44267:21)
    at Array.eval (plugin:obsidian-git:43674:60)
    at PromiseQueue.handleTask (plugin:obsidian-git:34225:20)
    at PromiseQueue.addTask (plugin:obsidian-git:34220:12)
    at Object.callback (plugin:obsidian-git:43674:41)
    at BK (app://obsidian.md/app.js:1:2040559)
    at t.onChooseItem (app://obsidian.md/app.js:1:2630500)
    at t.onChooseSuggestion (app://obsidian.md/app.js:1:1585009)
    at t.selectSuggestion (app://obsidian.md/app.js:1:1584559)
    at e.useSelectedItem (app://obsidian.md/app.js:1:1582418)
    at Object.func (app://obsidian.md/app.js:1:1579817)
    at e.handleKey (app://obsidian.md/app.js:1:754582)
    at e.onKeyEvent (app://obsidian.md/app.js:1:755838)
isGitInstalled @ plugin:obsidian-git:30392
setGitInstance @ plugin:obsidian-git:29730
init @ plugin:obsidian-git:44090
isAllInitialized @ plugin:obsidian-git:44239
createBackup @ plugin:obsidian-git:44267
eval @ plugin:obsidian-git:43674
handleTask @ plugin:obsidian-git:34225
addTask @ plugin:obsidian-git:34220
callback @ plugin:obsidian-git:43674
BK @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1
plugin:obsidian-git:30392 Error: spawnSync git ENOENT
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:891:24)
    at SimpleGit.isGitInstalled (plugin:obsidian-git:30384:57)
    at SimpleGit.checkRequirements (plugin:obsidian-git:30136:15)
    at ObsidianGit.init (plugin:obsidian-git:44094:44)
    at async ObsidianGit.isAllInitialized (plugin:obsidian-git:44239:7)
    at async ObsidianGit.createBackup (plugin:obsidian-git:44267:10)
```

### Steps to reproduce

Do something like a backup or so and see the error "Cannot run git command"

### Expected Behavior

The backup will be done

### Addition context

{
    "settings": {
        "commitMessage": "vault backup: {{date}} {{hostname}}",
        "commitDateFormat": "YYYY-MM-DD HH:mm:ss",
        "autoSaveInterval": 1,
        "autoPushInterval": 0,
        "autoPullInterval": 5,
        "autoPullOnBoot": true,
        "disablePush": false,
        "pullBeforePush": true,
        "disablePopups": false,
        "disablePopupsForNoChanges": false,
        "listChangedFilesInMessageBody": true,
        "showStatusBar": true,
        "updateSubmodules": false,
        "syncMethod": "merge",
        "customMessageOnAutoBackup": false,
        "autoBackupAfterFileChange": true,
        "treeStructure": false,
        "refreshSourceControl": true,
        "basePath": "",
        "differentIntervalCommitAndPush": false,
        "changedFilesInStatusBar": true,
        "showedMobileNotice": true,
        "refreshSourceControlTimer": 7000,
        "showBranchStatusBar": true,
        "setLastSaveToLastCommit": false,
        "submoduleRecurseCheckout": false,
        "gitDir": "",
        "showFileMenu": true,
        "authorInHistoryView": "full",
        "dateInHistoryView": true,
        "lineAuthor": {
            "show": false,
            "followMovement": "inactive",
            "authorDisplay": "initials",
            "showCommitHash": false,
            "dateTimeFormatOptions": "date",
            "dateTimeFormatCustomString": "YYYY-MM-DD HH:mm",
            "dateTimeTimezone": "viewer-local",
            "coloringMaxAge": "1y",
            "colorNew": {
                "r": 255,
                "g": 150,
                "b": 150
            },
            "colorOld": {
                "r": 120,
                "g": 160,
                "b": 255
            },
            "textColorCss": "var(--text-muted)",
            "ignoreWhitespace": false,
            "gutterSpacingFallbackLength": 5,
            "lastShownAuthorDisplay": "initials",
            "lastShownDateTimeFormatOptions": "date"
        },
        "autoCommitMessage": "vault backup: {{date}} {{hostname}}"
    },
    "pluginVersion": "2.26.0"
}

### Operating system

Windows

### Installation Method

Other

### Plugin version

2.26.0

**Comment by Vinzent03** [comment]
What exactly do you mean with "local github connection is working"? Do you have git installed and can run `git --version` in cmd or powershell?

**Comment by Malli88** [comment]
[obsidian.md-1725979273070.log](https://github.com/user-attachments/files/16946649/obsidian.md-1725979273070.log)
[debug info.txt](https://github.com/user-attachments/files/16946650/debug.info.txt)

**Comment by Malli88** [comment]
How we move one here?
Is there any information that I can provide to help solving the problem?

**Comment by Vinzent03** [comment]
Did you enter any value in the "Advanced" section in Obsidian? If so, try to clear them and restart Obsidian. If not, run `which git` in the terminal and enter that path as "Custom git binary path" in the plugin's settings, and please share that path here, and restart Obsidian.

**Comment by Malli88** [comment]
![image](https://github.com/user-attachments/assets/1260c34d-1bef-462f-ac26-5c3b7b0d699b)

which.exe git
C:\Users\mallmann\AppData\Local\Programs\Git\cmd\git.EXE

**Comment by Vinzent03** [comment]
And does it work, if you set that path as the value for "Custom git binary path" in the settings and restart Obsidian?

**Comment by Malli88** [comment]
Sorry for the late reply.
It is working now.... Just wondering why it worked already before and for some magical reasons stop working with known changes a fare as I know.
Thank you for your help sir!
