### ISSUE TITLE
[Bug]: Cannot run git command. Trying to run 'git'

### ISSUE THREAD

**Issue by zydxhs** [Vinzent03/obsidian-git#775]
### Describe the bug

When I execute the 'Git: List changed files' command, this prompt appears:
Cannot run git command. Trying to run 'git'

### Steps to reproduce

Press `CTRL + P`, input `Git: List changed files`, and press enter button.

### Expected Behavior

The normal behavior should be to list the modified files in the vault.

### Addition context

OS: Deepin 23
CPU: x86_64
core: 6.6.40-amd64-desktop-hwe
GIT: git version 2.45.2

installation method: linglong

### Operating system

Linux

### Installation Method

Other

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
Seems like linglong puts Obsidian in a container. You may try to set the installation path of git `which git` in the "custom git binary path" setting in Obsidian plugins settings. Otherwise it's not possible for Obsidian to access your git installation.

**Comment by zydxhs** [comment]
I tried reinstalling Obsidian using the deb package, but still encountered similar issues. It appears to be a bug in Deepin v23.

**Comment by zydxhs** [comment]
I am currently experiencing the same issue on Windows 10：
```
TypeError: Cannot read properties of undefined (reading'isBuffer)
```

**Comment by Hosseingsd** [comment]
For those who are so novice like me! and has same problem like me: Did you install [git](https://git-scm.com/downloads/win)? 
Don't be like me and assume " now that I installed GitHub Desktop application, there is no need to install git separately"! I was wrong! Installing **GitHub Desktop** does NOT install git on windows! These are separate things!

**Comment by Vinzent03** [comment]
@zydxhs Have you Git installed as described [here](https://publish.obsidian.md/git-doc/Installation#Windows)?

**Comment by zydxhs** [comment]
@Vinzent03 I have now confirmed that it caused by the plugin [Obsidian Local Images Plus](https://github.com/Sergei-Korneev/obsidian-local-images-plus).

After reinstalling 'Obsidian Local Images Plus', the issue has been resolved.
