### ISSUE TITLE
[Bug]: Is there any way to backup the root folder

### ISSUE THREAD

**Issue by wsmzjzz** [Vinzent03/obsidian-git#778]
### Describe the bug

I committed all of the files in my vault, but I cannot specify the remote to push to after I create an empty remote repo. Is there any way to backup and push the root vault to the remote instead of moving everything in a new folder?

### Steps to reproduce

.

### Operating system

macOS

### Installation Method

None

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
It should ask for a remote when you try to push with e.g. the "push" command. Otherwise there are commands for this like "edit remotes" or "set upstream branch"
