### ISSUE TITLE
Reload plugin settings on file change

### ISSUE THREAD

**Issue by Malli88** [Vinzent03/obsidian-git#779]
### Describe the bug

The Plugin settings of my obsidian plugins are not synced even they should be synced

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
Nothing i could find so fare
```

### Steps to reproduce

- Push on my main obsidian installation with some settings made in a plugin
- Take a look to GitHub, so I can see that everything is synced fine
- Open another installation of obsidian connected to the GitHub
- pull everything
- no plugin settings are pulled

.gitignore on both system
```
# OR only to exclude workspace cache
.obsidian/workspace.json

# to exclude workspace cache specific to mobile devices
.obsidian/workspace-mobile.json

# Add below lines to exclude OS settings and caches
.trash/
.DS_Store
```

### Expected Behavior

the plugin settings should be in sync

### Operating system

Windows

### Installation Method

None

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
That is currently the expected behavior, because the settings file is only read on startup. So restarting Obsidian should apply the new settings. But I'll think about changing that behavior.
