### ISSUE TITLE
[Bug]: Uncaught (in promise) Error: fatal: Invalid object name '"--pretty=format'.

### ISSUE THREAD

**Issue by dkbarn** [Vinzent03/obsidian-git#782]
### Describe the bug

I am unable to "Commit-and-sync" with a fresh install of Obsidian + Git plugin on Windows. 

On my first attempt at performing the "Commit-and-sync" action, it fails to commit, and the following is the output to the developer console.

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
loading Git plugin: v2.27.0
plugin:obsidian-git:314 obsidian-git: error: fatal: Invalid object name '"--pretty=format'.

plugin:obsidian-git:104 Uncaught (in promise) Error: fatal: Invalid object name '"--pretty=format'.

    at Object.action (plugin:obsidian-git:104:10649)
    at zF.exec (plugin:obsidian-git:104:10960)
    at eval (plugin:obsidian-git:103:6654)
    at new Promise (<anonymous>)
    at Xf.handleTaskData (plugin:obsidian-git:103:6543)
    at Xf.eval (plugin:obsidian-git:103:6169)
    at Generator.next (<anonymous>)
    at a (plugin:obsidian-git:100:11259)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
plugin:obsidian-git:314 obsidian-git: error: fatal: Invalid object name '"--pretty=format'.
```

### Steps to reproduce

1. Install Obsidian v1.6.7 on Windows 10
2. Install and enable Git Plugin v2.27.0
3. Exit Obsidian
4. Install Git for Windows v2.46.2.windows.1
5. Create a new repo on GitHub
6. Run the following commands in Git Bash:
```
cd "C:\Users\<username>\Documents\Obsidian Vault\"
git init
git add .obsidian
git commit -m "Initial commit of obsidian settings"
git branch -M main
git remote add origin https://github.com/path/to/my/vault.git
git push -u origin main
```
7. When prompted, authenticate using browser
8. Open Obsidian, create a new note
9. Go to "Open Git source control"
10. Push "Commit-and-sync" button
11. Commit fails, error is written to developer console

### Addition context

Debug info copied from settings:
```
{
    "settings": {
        "commitMessage": "vault backup: {{date}}",
        "commitDateFormat": "YYYY-MM-DD HH:mm:ss",
        "autoSaveInterval": 0,
        "autoPushInterval": 0,
        "autoPullInterval": 0,
        "autoPullOnBoot": false,
        "disablePush": false,
        "pullBeforePush": true,
        "disablePopups": false,
        "disablePopupsForNoChanges": false,
        "listChangedFilesInMessageBody": false,
        "showStatusBar": true,
        "updateSubmodules": false,
        "syncMethod": "merge",
        "customMessageOnAutoBackup": false,
        "autoBackupAfterFileChange": false,
        "treeStructure": false,
        "refreshSourceControl": true,
        "basePath": "",
        "differentIntervalCommitAndPush": false,
        "changedFilesInStatusBar": false,
        "showedMobileNotice": true,
        "refreshSourceControlTimer": 7000,
        "showBranchStatusBar": true,
        "setLastSaveToLastCommit": false,
        "submoduleRecurseCheckout": false,
        "gitDir": "",
        "showFileMenu": true,
        "authorInHistoryView": "hide",
        "dateInHistoryView": false,
        "lineAuthor": {
            "show": false,
            "followMovement": "inactive",
            "authorDisplay": "initials",
            "showCommitHash": false,
            "dateTimeFormatOptions": "date",
            "dateTimeFormatCustomString": "YYYY-MM-DD HH:mm",
            "dateTimeTimezone": "viewer-local",
            "coloringMaxAge": "1y",
            "colorNew": {
                "r": 255,
                "g": 150,
                "b": 150
            },
            "colorOld": {
                "r": 120,
                "g": 160,
                "b": 255
            },
            "textColorCss": "var(--text-muted)",
            "ignoreWhitespace": false,
            "gutterSpacingFallbackLength": 5
        },
        "autoCommitMessage": "vault backup: {{date}}"
    },
    "pluginVersion": "2.27.0"
}
```

### Operating system

Windows

### Installation Method

None

### Plugin version

2.27.0

**Comment by Vinzent03** [comment]
No I think the format is correct. I have the same command in my logs, but for me everything is working.
![image](https://github.com/user-attachments/assets/3a79f4c4-3e7f-437b-a423-096f0c9b7d8e)

I'm on linux and you're on Windows, but the simple-git dependency hasn't changed for quite some releases and I think if it would impact all Windows machines I've gotten more of these issues. So I don't know that this causes.

**Comment by Vinzent03** [comment]
I had to switch to my own work, to faster ship a fix I've made to simple-git, but that's already merged and released by simple-git as well. So you're right, I've switched now to the new simple-git versions on the master branch. So you can try the newest version out (remember to install the new version with `pnpm install`)
I doubt git has introduced any breaking changes in this regard, though.

**Comment by Vinzent03** [comment]
I guess works fine for me. I get the following stdout: `'òòòòòò 750941ab3ff9e2f7e592a98847e720ea19ddbca6 ò 2024-10-10T11:10:53+02:00 ò 128 ò HEAD -> Test ò  ò Vinzent ò vinzent03@proton.me òò'`
This works for me on **Windows** and Linux.
