### ISSUE TITLE
How to wipe data/cache and start over?

### ISSUE THREAD

**Issue by mr-september** [Vinzent03/obsidian-git#784]
### Describe the bug

I've been trying for hours to initialize this plugin to no avail It has been very frustrating.

I have followed both the documentations https://publish.obsidian.md/git-doc/Getting+Started

and watched youtube videos https://www.youtube.com/watch?v=5YZz38U20ws

Nothing works. 

I suspect that at some point, trying too many different approaches has set up corruptions/incompatibilities.

I tried to reset this by uninstalling and re-installing and re-enabling the plugin, but it still seems to remember all my old settings and """progress""".

So how can I make my system/Obsidian fully forget everything about this plugin before starting again?

### Operating system

Windows

### Plugin version

2.27.0

**Comment by jameswilliamknight** [comment]
I've been pulling my hair out... I can't even find the .git folder!

**Comment by mr-september** [comment]
Where are they? I've checked my install path (C:\Users\<username>\AppData\Local\Obsidian) and there's only 2 subfolders - locales and resources. Gone all the way deep and still couldn't find plugins or .git
