### ISSUE TITLE
Backup command no longer exist

### ISSUE THREAD

**Issue by hhemied** [Vinzent03/obsidian-git#785]
I used to use the command git backup to `stage`, `commit` and, `push` to my git repo.
Now, I can't find this command anymore.

**Comment by Vinzent03** [comment]
It's now now called Commit–and–sync
Duplicate of #774

**Comment by hhemied** [comment]
I assume based on [THIS](https://publish.obsidian.md/git-doc/Start+here), the backup command is no longer available and the one to use is `commit-and-sync`.

**Comment by hhemied** [comment]
Thanks @Vinzent03 , you are quicker ;)
