### ISSUE TITLE
[feature]  Make auto commit a per device setting

### ISSUE THREAD

**Issue by iamashwin99** [Vinzent03/obsidian-git#789]
The current settings allow only to enabling the plugin not on a per-device basis. It might be useful to allow the setting of auto commits also on a per-device level. This way on my phone I can always have auto-pull but never commit (causing a potential merge conflict on the other device).

**Comment by Vinzent03** [comment]
If you only pull on your mobile device, I suspect you just get the merge conflicts on your mobile device. So I don't recommend that. I don't plan to make this setting a per device setting. If you still want to accomplish this, you can use a different Obsidian config directory under Files and links for your mobile device.
