### ISSUE TITLE
[Bug]: Clone existing repo command not working

### ISSUE THREAD

**Issue by HarshChakalasiya** [Vinzent03/obsidian-git#798]
### Describe the bug

I updated my git plugin to 2.28.0 and I tried to clone the repo using command and when I hit the clone command it doesn't open the another pop up for repo link.

In previous release, it was working fine. 

### Steps to reproduce

1. Check your git plugin version. If it is 2.28.0 then it should be fine otherwise update it or reinstall it.
2. After that create or open a vault and hit `Git: Clone an existing remote repo` command.

### Expected Behavior

After hitting clone repo command, pop up should be opened for remote repo link.

### Operating system

Linux

### Installation Method

None

### Plugin version

2.28.0

**Comment by massaraksh-yandex** [comment]
I have same issue on my Ipad Obsidian

**Comment by iliralushi** [comment]
Same issue in both Debian and Android

**Comment by Vinzent03** [comment]
Should be solved now in v2.28.1

**Comment by iliralushi** [comment]
Works, thanks!

**Comment by HarshChakalasiya** [comment]
Works Thank you
