### ISSUE TITLE
Clone repository 

### ISSUE THREAD

**Issue by piroozpishahang** [Vinzent03/obsidian-git#799]
### Describe the bug

Hi my friend. Recently the last version is not working as well as pre version. I can't clone any repository. It's not only don't work on phone but on PC have same problem.

### Steps to reproduce

Clone

### Operating system

Windows

### Installation Method

None

### Plugin version

2.28

**Comment by Vinzent03** [comment]
Please update to the latest version I released just some minutes ago.
