### ISSUE TITLE
[Request]: Display binary files (images) instead of showing the diff

### ISSUE THREAD

**Issue by Sparticuz** [Vinzent03/obsidian-git#801]
### Describe the bug

Open the image itself instead of opening the diff

### Steps to reproduce

When in tree-view, selecting a file will open the diff. This is fine for non-binary files, but binary files should just open the file.

### Expected Behavior

The image is displayed

### Addition context

![image](https://github.com/user-attachments/assets/1229438f-4a4c-4c40-b796-afa6cd8d11f2)

versus

![image](https://github.com/user-attachments/assets/488d8dd7-d372-49cc-8ab1-c3cc401e81b7)

### Operating system

Windows

### Installation Method

None

### Plugin version

latest

**Comment by Vinzent03** [comment]
Now fixed in v2.31.0 :tada:

**Comment by Sparticuz** [comment]
Thank you!
