### ISSUE TITLE
[MayBe BUG]: git-lfs commond not found

### ISSUE THREAD

**Issue by RWDai** [Vinzent03/obsidian-git#818]
### Describe the bug

open git tab:
<img width="303" alt="image" src="https://github.com/user-attachments/assets/aa302475-2fa3-4320-994f-0f0486a49e05">

but in terminal:
<img width="596" alt="image" src="https://github.com/user-attachments/assets/dc77855e-0ef1-4728-8b64-1bc3005d5f20">

Perhaps there's something wrong with the environment variable settings? Anyway, I need help. Thank you for your plugin

### Steps to reproduce

open git tab

### Operating system

macOS

### Installation Method

None

### Plugin version

2.30.0

**Comment by RWDai** [comment]
Restarting Obsidian didn't work, but reloading with new environment variables in Git configuration solved the issue

**Comment by Satar07** [comment]
I searched here and found the link to solve the problem by tracking previous issues: https://publish.obsidian.md/git-doc/Integration+with+other+tools#Git+Large+File+Storage
