### ISSUE TITLE
[Bug]: DEFAULT_WIN_GIT_PATH introduced in 2.30.0 affects MacOS users and results in startup failure

### ISSUE THREAD

**Issue by theRuslan** [Vinzent03/obsidian-git#820]
### Describe the bug

[Bug]: DEFAULT_WIN_GIT_PATH introduced in 2.30.0 affects MacOS users and results in startup failure because there is no such path in macos systems.

<img width="384" alt="Screenshot 2024-11-28 at 17 32 10" src="https://github.com/user-attachments/assets/617d24a6-d1a0-43ce-96eb-ce93a50c455d">

At the same time git bin path from settings is present but not taken into account.

<img width="802" alt="Screenshot 2024-11-28 at 17 32 46" src="https://github.com/user-attachments/assets/39e00ee5-8ee9-40d1-a632-80294f5cf1c3">

### Steps to reproduce

1. Start Obsidian on MacOS.
2. Upgrade to 2.30.0

### Operating system

macOS

### Installation Method

None

### Plugin version

2.30.0

**Comment by Vinzent03** [comment]
Thanks for the report! Should be fixed now in v2.30.1
