### ISSUE TITLE
[Bug]: Unable to auth to Github via ssh on MacOS using 1password ssh-agent

### ISSUE THREAD

**Issue by liftconfig** [Vinzent03/obsidian-git#824]
### Describe the bug

- .ssh/config is correctly configured to use 1password ssh agent:
Host *
  IdentityAgent "~/Library/Group Containers/xxxxxxxxx.com.1password/t/agent.sock"

- Output of ssh-add shows correct ssh key:
SSH_AUTH_SOCK=~/Library/Group\ Containers/xxxxxxxxx.com.1password/t/agent.sock ssh-add -l

- Access to repo via git cli works
- Running git operations on same repository within Obsidian causes permission error

### Relevant errors (if available) from notifications or console (`CTRL+SHIFT+I`)

```shell
git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
```

### Steps to reproduce

Using Git in Obsidian to try and access remote github repository via ssh while using 1password ssh-agent

### Operating system

macOS

### Installation Method

Other

### Plugin version

2.30.1

**Comment by Vinzent03** [comment]
I guess you have some setup for your ssh-agent in your .bahsrc, .zshrc or similar. Could you share that? These scripts only affect your shell and not Obsidian (unless you start Obsidian from the terminal, in that case it should work).
For now, I suggest you to set the `SSH_AUTH_SOCK` env variable yourself in the plugins settings.

**Comment by liftconfig** [comment]
Setting env var SSH_AUTH_SOCK="~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock" in the plugin or launching Obsidian from terminal didn't resolve the issue. I edited the remote (option: Git: Edit Remotes) and changed the remote from ssh to https as a work around.

**Comment by liftconfig** [comment]
I've changed it to the following:

SSH_AUTH_SOCK=/Users/<username>/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

Obsidian is definitely using the correct ssh agent now - when I try push or pull get the 1password prompt to permit Obsidian to use my key. After permitting, I still hit the same fatal error in the OP. 

<img width="316" alt="image" src="https://github.com/user-attachments/assets/e941b5cf-2246-496b-a375-24586da025aa" />

**Comment by Vinzent03** [comment]
Great that it's able to interact with 1passwort somehow, at least!
You may check the console in addition to the notifications, but I doubt there is more information.
I've read the 1password documentation for their ssh agent, but with setting the SSH_AUTH_SOCK environment variable, everything should be correctly configured.
So I don't know any further steps on how to fix this, sorry.

**Comment by liftconfig** [comment]
Thanks Vincent, closing this as a workaround is available (use HTTPS rather than SSH)

**Comment by aeddi** [comment]
Workaround here: https://github.com/Vinzent03/obsidian-git/issues/876#issuecomment-3281077434
