### ISSUE TITLE
[Bug]: commit message box is empty after commit-and-sync 

### ISSUE THREAD

**Issue by dawnfantasy** [Vinzent03/obsidian-git#828]
### Describe the bug

Commit Message box is empty after commit-and-sync.

### Steps to reproduce

1. make changes to Commit Message box
2. click Commit-and-sync button

### Expected Behavior

Either keep the altered message or restore the predefined message from setting.

### Operating system

Windows

### Installation Method

None

### Plugin version

2.30.1

**Comment by Vinzent03** [comment]
I've added it here by design: https://github.com/Vinzent03/obsidian-git/commit/5f294a466d62571887fbe4a6c55478990bc9c26c#diff-545e1bfb7b25fa66b74b7349ff9b93839568cbedf2ddb5a16d2593d9439d07edR39
But I will change it to reset to the template from the setting after commit :+1:

**Comment by Vinzent03** [comment]
Now fixed in v2.31.0 :tada:
