### ISSUE TITLE
[Bug]: Unable to configure authentication through Authentication/Commit Author Options

### ISSUE THREAD

**Issue by olliezhu** [Vinzent03/obsidian-git#829]
### Describe the bug

According to the [Getting Started documentation](https://publish.obsidian.md/git-doc/Getting+Started#Clone+via+plugin), I should be able to configure my GitHub username and password (personal access token) in the "Authentication/Commit Author" section of Options. I see a "Commit Author" section but no options to configure authentication.

### Steps to reproduce

- Open up Options for the Git community plugin
- Confirm that there does not exist an option to configure authentication

### Expected Behavior

The Options for this plugin should contain a section for "Authentication/Commit Author".

### Addition context

Obsidian v1.7.7

I was able to work around this by manually configuring remote, authentication, commit author, and first commit/push:
- Cloning my existing remote repository (I happened to do with with the Git plugin command)
- `git remote remove origin`
- `git remote add origin https://<personal access token>@github.com/<username>/<repository>`
- `git config user.name` and `git config user.email`
- `git add .gitignore`, commit, and `git push --set-upstream origin main`

Opening Obsidian at the path of this Git repository is now authenticated and properly commit-and-syncs with the plugin.

### Operating system

macOS

### Installation Method

None

### Plugin version

2.30.1

**Comment by Vinzent03** [comment]
The documentation you are referring to is for mobile devices and not for desktop Obsidian. Please refer to this documentation instead: https://publish.obsidian.md/git-doc/Authentication

**Comment by olliezhu** [comment]
Thanks for the clarification!
